---
common_packages_debian:
  - curl
  - ca-certificates
  - jq
  - iproute2
  - rsync

common_packages_redhat:
  - curl
  - ca-certificates
  - jq
  - iproute
  - rsync

common_timesync_package: chrony

install_kvm_tools: true

kvm_packages_debian:
  - qemu-system-x86
  - qemu-utils
  - ovmf
  - cloud-image-utils

kvm_packages_redhat:
  - qemu-kvm
  - qemu-img
  - edk2-ovmf
  - cloud-utils
