---
- name: Install Docker (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ docker_pkg_debian }}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == 'Debian'

- name: Install Docker (RHEL/Fedora)
  ansible.builtin.dnf:
    name: "{{ docker_pkg_redhat }}"
    state: present
  when: ansible_facts.os_family == 'RedHat'

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
